### ISSUE TITLE
Ore Gen configs do not seem to have any effect

### ISSUE THREAD

**Issue by Apoc1992** [TeamMetallurgy/Atum2#406] opened 2023-01-15 03:30 UTC
Hi all,

I am trying to increase the ore gen in the Atum dimension specifically, and I see that there are specific configs for doing so. That said, changing the configs settings does not seem to have any effect. I have set the both the "vein size" and "count" settings for all ores to max (64), but am still only getting vanilla style generation. I have changed other configs in the file and have gotten the expected results, so I do not believe that the file itself is to blame. Am I missing something, or perhaps is the ore gen customization not yet functioning in the mod? 

Thanks for your help,

![2023-01-14_20 23 07](https://user-images.githubusercontent.com/105953353/212521534-2bbe2445-98b2-4fe8-b1a8-6e6d1848e6ce.png)
![2023-01-14_20 23 09](https://user-images.githubusercontent.com/105953353/212521536-e2713754-c6f6-436f-a386-2c5f6693aa77.png)

**Comment by GirafiStudios** [comment] 2023-01-15 08:46
Duplicate of https://github.com/TeamMetallurgy/Atum2/issues/359
Can´t really do anything about it, due to how things are loaded in Forge nowadays. The configs will be gone in the future.
You´ll hve to use one of the mods that can alter ore generation :)

**Closed by GirafiStudios** 2023-01-15 08:46 UTC

**Comment by Apoc1992** [comment] 2023-01-15 14:29
Ok, thanks!
