### ISSUE TITLE
Atum 2 Sarcophagus crash (tile entity)

### ISSUE THREAD

**Issue by TheWitherlord** [TeamMetallurgy/Atum2#191] opened 2020-07-12 13:29 UTC
There seems to be an issue with the Blockheads mod and the tile entity of the sarcophagus from the Atum.

Atum version: Atum-1.15.2-2.1.1.jar
 Minecraft Version: 1.15.2
Forge Version: 1.15.2 - 31.2.31

Crash Report:
https://gist.github.com/TheWitherlord/c8add0e5464c237a921d613c31f696e7

Latest Log: https://gist.github.com/TheWitherlord/bda2ab14d5deee2b040500f03f048fe0

Hope this is enough info to understand the problem?

**Comment by sscards55** [comment] 2020-07-12 13:31
Duplicate of #189 and #190.

**Comment by GirafiStudios** [comment] 2020-07-12 13:43
As sscards said ^
You can grab a Jenkins build with a fix here:
https://jenkins.girafi.dk/job/Team%20Metallurgy%20Mods/job/Atum%202/job/Atum%202%201.15.2%20Jenkins/
A new build with probably be out on CurseForge later today

**Closed by GirafiStudios** 2020-07-12 13:43 UTC
