### ISSUE TITLE
Consistent Crashing in Atum 2

### ISSUE THREAD

**Issue by Marrowisp** [TeamMetallurgy/Atum2#326] opened 2021-08-06 05:54 UTC
I haven't been able to explore Atum very much yet because my game crashes not long after walking around. Crash reports are attached, there seems to be a problem with limestone_brick_large. The pack is Better Minecraft Plus (1) and I don't believe flywheel is apart of this pack, but I could be wrong. Please advise, thank you. 
 
[crash-2021-08-04_00.21.21-client.txt](https://github.com/TeamMetallurgy/Atum2/files/6943323/crash-2021-08-04_00.21.21-client.txt)
[crash-2021-08-05_23.33.55-client.txt](https://github.com/TeamMetallurgy/Atum2/files/6943324/crash-2021-08-05_23.33.55-client.txt)
[crash-2021-08-04_00.16.47-client.txt](https://github.com/TeamMetallurgy/Atum2/files/6943325/crash-2021-08-04_00.16.47-client.txt)

**Comment by sscards55** [comment] 2021-08-06 05:55
This looks like #325

**Comment by sscards55** [comment] 2021-08-06 05:57
Could you update flywheel to 0.2.1 and disable the chunk access optimization option

**Comment by GirafiStudios** [comment] 2021-08-06 12:11
Duplicate of #325

**Closed by GirafiStudios** 2021-08-06 12:11 UTC
