### ISSUE TITLE
Crash in Atum - atum.world.biome.AtumBiomeProvider

### ISSUE THREAD

**Issue by SharkieTV** [TeamMetallurgy/Atum2#318] opened 2021-07-28 08:32 UTC
Only a few of my Players are experiencing a Crash in your Dimension. Sorry if this is a Duplicate.

[Crash](https://pastebin.com/rmDJkJYs)
[Latest.log](https://cdn.discordapp.com/attachments/869767317410701314/869858893164077088/latest.log)
[Modpack](https://www.curseforge.com/minecraft/modpacks/better-mc-plus)

**Comment by sscards55** [comment] 2021-07-28 08:47
duplicate of #295

**Comment by sscards55** [comment] 2021-07-28 08:47
A mod is adding biomes and not registering them correctly.

**Closed** 2021-07-28 09:15 UTC
