### ISSUE TITLE
[1.15.2] Client Crash after searching JEI

### ISSUE THREAD

**Issue by mr-poyo** [TeamMetallurgy/Atum2#190] opened 2020-07-12 01:29 UTC
Forge: 31.2.31
Atum Version: Atum-1.15.2-2.1.1.jar

Hello,
I was playing on my minecraft server with my custom modpack and at one point I typed @atum in JEI to search blocks, but the moment I began typing it, my client crashed. Server was fine, it seemed to be a client-side crash.

crash report: https://pastebin.com/wApuh3WF

**Comment by GatekeeperTDS** [comment] 2020-07-12 02:55
This may be the same issue I experienced earlier.

#189

**Comment by mahjerion** [comment] 2020-07-12 03:00
Seems to be a common occurrence. https://pastebin.com/pxFznTER

**Comment by GirafiStudios** [comment] 2020-07-12 10:35
Duplicate of https://github.com/TeamMetallurgy/Atum2/issues/189

**Closed by GirafiStudios** 2020-07-12 10:35 UTC
