### ISSUE TITLE
Atum 2 Portal doesnt work with Mythic Botany Mod

### ISSUE THREAD

**Issue by MrNoe93** [TeamMetallurgy/Atum2#344] opened 2021-09-12 06:56 UTC
Some interaction between the Atum 2 mod and the Mythic Botany Mod makes the Atum 2 portal not teleport the player.  It forms just fine but doesnt do anything when the player steps in.  Tried with just those two mods (and required dependencies) and still got the same result.

Forge: 36.2.0
Atum 2: 2.2.7
Mythic Botany: 1.4.9

**Comment by sscards55** [comment] 2021-09-12 10:03
Please open an issue in Mythic Botany's issue page if you have not already and reference this issue.

**Comment by noeppi-noeppi** [comment] 2021-09-12 15:13
The issue is not reproducible for me. It would be interesting to know the thoughts you had when telling them to open the issue on my issue tracker. Maybe that helps resolving it. @sscards55

**Comment by MrNoe93** [comment] 2021-09-12 15:19
Updating MythicBotany to 1.4.10 fixed the issue for my fyi.

**Closed** 2021-09-12 15:30 UTC
