### ISSUE TITLE
FPS decline when look at a Desert Wolf, while having The One Probe installed

### ISSUE THREAD

**Issue by mcBegins2Snow** [TeamMetallurgy/Atum2#116] opened 2019-05-22 01:16 UTC
Mod version: 2.0.7
Screenshots
![2019-05-22_09 11 56](https://user-images.githubusercontent.com/37864486/58140515-23306180-7c72-11e9-8a55-3174ea2a21c8.png)
![2019-05-22_09 12 03](https://user-images.githubusercontent.com/37864486/58140516-23306180-7c72-11e9-92f7-15e70fe5250c.png)

**Comment by GirafiStudios** [comment] 2019-05-22 06:42
Thank you for your report!
![mEnGnf7](https://user-images.githubusercontent.com/6305377/58152638-53c1cc80-7c6d-11e9-86af-fe8bebb88bff.png)
![VDGK0JJ](https://user-images.githubusercontent.com/6305377/58152685-70f69b00-7c6d-11e9-970c-3dfa0b3152be.png)
As the screenshots show, I cannot reproduce this. It's most likely caused by the the mod you have, that adds the 3D render at the top
![8AZbVcW](https://user-images.githubusercontent.com/6305377/58152741-94214a80-7c6d-11e9-85ea-fcdbe6cb1db7.png)

**Comment by mcBegins2Snow** [comment] 2019-05-22 07:36
I found a reason. The FPS decline came from The One Probe's entity model render. When hidden (enter `/topneed`, then click `Needed`), The FPS became normal. Instead of large entity model.
I don't know how to close entity model render for The One Probe mod.

**Comment by GirafiStudios** [comment] 2019-05-22 08:22
Oh it's The One Probe? You're right that is quite a huge FPS drop, I'll see if I can do anything on our side (Since it does not happen for vanilla wolfs)

**Comment by GirafiStudios** [comment] 2019-05-22 10:05
Fixed by https://github.com/TeamMetallurgy/Atum2/commit/9c26ea9c6c3051b69722da49d827adf3d9604153
Turned out to be a super weird cause, but managed to find a workaround (Thanks to @lclc98)
The One Probe might be creating a new entity when doing the 3D rendering, which is a bad thing..
But yea at least the FPS drop is completely gone now.

**Closed by GirafiStudios** 2019-05-22 10:05 UTC
