### ISSUE TITLE
Possible Camel Problems

### ISSUE THREAD

**Issue by 63502** [TeamMetallurgy/Atum2#84] opened 2019-04-13 05:33 UTC
Camels work just fine when stepping up 1 block at a time, but they seem to be unable to properly navigate sand layers. When walking on them, the camel will just get stuck and rubber band in place until I dismount.

Mod version: 2.0.3
Forge Version: 14.23.5.2835

**Comment by GirafiStudios** [comment] 2019-04-13 07:28
Thank you for your report!
Do you have a way to reliably reproduce this?

**Comment by 63502** [comment] 2019-04-13 23:23
I should be able to, but I started running into a ticking world crash that is preventing me from testing in atum.

When I make a world with only atum and forge the game crashes after a few seconds of exploration after entering atum. With my full modded instance the game does the same thing, but the world freezes instead of crashing outright.

[Crash Log from clean testing instance](https://gist.github.com/63502/2d6add8231a9bf1a073448195e4e9660)
[Crash Log crash log extracted from game log of full modded instance](https://gist.github.com/63502/76914cc4efc730e68b97ec0fe0095e55)

I attempted to test the camel movement problem in the overworld, but everything worked just fine. I may have just run into a random error or mod interaction. I'll see what I can do about testing for mod interactions when I have time.

**Comment by GirafiStudios** [comment] 2019-04-14 19:00
From what I can tell your crash is because of a problem in Forge. Please update to Forge 14.23.5.2836, or any version before 14.23.5.2832.

About the camels - I can't really do much about it, if I can't reproduce it.
Testing for weird mod interactions (When you have time) would be much appreciated :)

**Comment by GirafiStudios** [comment] 2019-05-01 19:55
Closing as not enough information have been provided about the issue.
If you find a way to reproduce it, please open a new issue :)

**Closed by GirafiStudios** 2019-05-01 19:55 UTC
Labels: More Information Needed
