### ISSUE TITLE
Crash on Chunk Generation with Ruin19

### ISSUE THREAD

**Issue by 4cqker** [TeamMetallurgy/Atum2#313] opened 2021-07-16 04:38 UTC
[crash-2021-07-16_13.37.46-server.txt](https://github.com/TeamMetallurgy/Atum2/files/6827844/crash-2021-07-16_13.37.46-server.txt)

![image](https://user-images.githubusercontent.com/62732692/125892582-5f468a42-6aad-44dd-b8a6-aeb901ede7c2.png)

Entered Atum and a certain Ruin must have tried to generate that caused a crash. This happened near enough to the portal that I can't escape to the overworld, so i'm soft locked and can't load my world anymore.

**Comment by GirafiStudios** [comment] 2021-07-16 09:42
Delete your config (If you haven´t changed anything in it) or set the Ruin Amount to 17 in the config. Not sure how yours are set to 19, it´ve never been that by default before.
Duplicate of https://github.com/TeamMetallurgy/Atum2/issues/307

**Closed by GirafiStudios** 2021-07-16 09:42 UTC
