### ISSUE TITLE
Atum Crashes when desert wolves appear

### ISSUE THREAD

**Issue by Smackmyhams** [TeamMetallurgy/Atum2#226] opened 2021-03-26 02:39 UTC
Hopefully this time the crash report uploads. The game seems to crash when a Desert wolf appears. Can only log in for a second before the client crashes.
[crash-2021-03-21_13.27.57-client.txt](https://github.com/TeamMetallurgy/Atum2/files/6208982/crash-2021-03-21_13.27.57-client.txt)
](url)

**Comment by sscards55** [comment] 2021-03-26 04:09
I don't think 1.12 is supported anymore, but try removing the Entity Culling mod to see if it fixes it.
Also get rid of NEIDs regardless, you will have to get rid of your world, the reason for this is if you update almost any of your mods it will corrupt your world. Use JEID instead it's written on the NEIDs page.

**Comment by GirafiStudios** [comment] 2021-03-26 13:29
Duplicate of https://github.com/TeamMetallurgy/Atum2/issues/157
Also get rid of NEID as sscards said, might help.

**Closed by GirafiStudios** 2021-03-26 13:29 UTC
