### ISSUE TITLE
Chunk genereration error in The Atum and End Dimension

### ISSUE THREAD

**Issue by EggSpeen** [TeamMetallurgy/Atum2#311] opened 2021-07-13 10:19 UTC
Every time I load in to my minecraft world and go to the Atum dimension, the chunks that have been already generated wont be aligned with the newly generated chunks, same with the End Dimension but im not sure if the nether suffers the same issue, for the overworld it still generates normally since it uses the terraforge mod generation

and this is what it looks like:
![ChunkError](https://user-images.githubusercontent.com/87365461/125434733-3786bc23-f7c2-42e8-83e0-185846271d8a.png)

![2021-07-13_18 02 42](https://user-images.githubusercontent.com/87365461/125434851-b6e514cd-c5c6-4ad1-8ab9-5ef7986443e1.png)
 
And also before I downloaded this mod, The End dimension didn't have any problems on generating chunks

**Comment by TelepathicGrunt** [comment] 2021-07-28 20:19
Chunk borders in Atum itself may be caused by this line which causes the biome layout to change every time the game is restarted which caused chunk borders if the new biome has a different height 
https://github.com/TeamMetallurgy/Atum2/blob/de3b83c5c3ec8552b5eb9d05dca161b4b1cae5c2/src/main/java/com/teammetallurgy/atum/world/biome/AtumBiomeProvider.java#L35

@GirafiStudios I am making a PR to Atum2 to help fix the wrong biome registry being use. I can also fix the seed thing so it uses the world's seed for the chunk generator and biome source but it requires 1 mixin. Would that be alright? The mixin needed is this https://github.com/TelepathicGrunt/WorldBlender/blob/latest-released/src/main/java/com/telepathicgrunt/worldblender/mixin/dimensions/DimensionGeneratorSettingsMixin.java

**Comment by GirafiStudios** [comment] 2021-07-28 20:36
Sounds good about wrong biome registry fix, would be much aprpeciated!

As for the Mixin, I would preferably like to avoid it. Been a while since I looked at this, but couldn´t we just set our own seed (like now), and then save it to the DimensionData (See world/AtumDimensionData)? :)

**Comment by TelepathicGrunt** [comment] 2021-07-28 20:56
that could work but you'll have to find a way to grab that seed in the biome source's constructor. Also consider what happens if a person uses datapacks to make multiple atum2 dimensions. That means your biome source would be ran multiple times and creates 2 random seeds. One of which will override the other seed. In theory lol. (of course that's an edge case thing as I haven't see anyone make copies of modded dimensions by datapack yet)

**Comment by GirafiStudios** [comment] 2021-07-28 21:04
Oh yea, that´s true. That would require a ServerWorld, in order to get the dimension data.
If you can´t find a workaround for that, go ahead with the Mixin. I´m not too fond of it, but not much that can be done, without Forge making a patch.

If the user decides to do that, it´s their fault for messing it up. I do not intend to support that.

**Comment by GirafiStudios** [comment] 2021-07-28 22:16
Should be fixed by https://github.com/TeamMetallurgy/Atum2/commit/bb61b74c4f60d675486cf88792372dc4ed9f587c

**Closed by GirafiStudios** 2021-07-28 22:16 UTC

**Comment by TelepathicGrunt** [comment] 2021-07-28 22:28
hmm actually the chunk generation might be also due to the randomizing seed issue (i noticed the chunkgenerator constructor also does a random seed). I'll try and make a forge pr to expose the world seed for modders to use but we will see how long it takes for forge to merge it lol

**Comment by GirafiStudios** [comment] 2021-07-28 22:32
That sounds great with the Forge PR!
With the prospect of possibly getting a fix in Forge, I wouldn´t mind having mixins as temporary workarounds. If that would be something, you would be willing to do, that would be very much appreciated :)
