### ISSUE TITLE
Half pyramid

### ISSUE THREAD

**Issue by aycfes** [TeamMetallurgy/Atum2#73] opened 2019-03-22 17:58 UTC
exactly what's in the title (actually, 1 block slice more than half, so something among the lines of 1.1/2)
![2019-03-22_13 31 07](https://user-images.githubusercontent.com/38796165/54843094-5bd3af00-4cb2-11e9-9498-73e2bfb3e1bc.png)
![2019-03-22_14 02 36](https://user-images.githubusercontent.com/38796165/54843095-5bd3af00-4cb2-11e9-9def-6267516ade61.png)

also, the treasure maps seem to lead to sandy holes, just places where the ground has deeper sand, with no loot or anything, idk if it is a bug, but it is a thing.

ik of the new version you just released, and am already using it, (not at the time of the screenshots) but since there was no mention of either in the changelog, i'll assume they're still issues.

**Comment by GirafiStudios** [comment] 2019-03-22 18:01
The Graverobber's Map is intended to not always lead to a pyramid.

Did you find this in a world created before 2.0.2, after updating to 2.0.2?

**Comment by aycfes** [comment] 2019-03-22 18:04
nope, full 2.0.1

**Comment by GirafiStudios** [comment] 2019-03-22 18:05
Is this in singleplayer or on a server?

**Comment by aycfes** [comment] 2019-03-22 18:05
singleplayer

**Comment by GirafiStudios** [comment] 2019-03-22 18:08
Can I get you to pastebin the log?

**Comment by aycfes** [comment] 2019-03-22 18:10
if this is what you meant, most definently.
[2019-03-22-1.log.gz](https://github.com/TeamMetallurgy/Atum2/files/2997755/2019-03-22-1.log.gz)

**Comment by GirafiStudios** [comment] 2019-03-22 18:19
That was what I meant, yes.
Unfortunately there was zero information in there.
It can be one of two things though. Either simply just a generation error, due to your computer not being able to generate the chunk quick enough (Can happen in vanilla too)
Or some incompatibility with another mod.
Without a way to reproduce it, I can't really look into doing anything about it :/

**Comment by aycfes** [comment] 2019-03-22 18:23
well, i'll be sure to tell you if i find more of them or find out any insight, otherwise, 'tis prolly just thanos having a midlife crisis

**Comment by GirafiStudios** [comment] 2019-03-22 18:25
Sounds good, appreciate it :)
I'll close this for now, but feel free to open a new issue if you find a way to reproduce it. Or comment here, if it happens to you again.

**Closed by GirafiStudios** 2019-03-22 18:25 UTC
