### ISSUE TITLE
ticking entity crash on single player world with newest 1.16.5 version of mod 

### ISSUE THREAD

**Issue by thiccmeme** [TeamMetallurgy/Atum2#232] opened 2021-05-12 02:30 UTC
[2021-05-11-3.log.gz](https://github.com/TeamMetallurgy/Atum2/files/6463007/2021-05-11-3.log.gz)

attached is a log of the crash

the issue may be an incompatibility with other mods, however, I still thought it necessary to submit this report. I have not enough crashes installed thus the game did not crash entirely and why a log is attached instead of a crash report.

version of mod is 1.16.5-2.20 

and forge is 1.16.5 version 36.1.16

optfine is installed along with a variety of other mods

**Comment by sscards55** [comment] 2021-05-12 02:43
The crash is not related to Atum. It's caused by Epic Fight Mod. Please report it to their issue tracker. 
Also please don't compress your logs into an archive.

**Comment by MarioSMB** [comment] 2021-05-12 03:54
I'd just like to add a correction to the previous statement: logs are *automatically* compressed by the game when a new one is created, the reporter has merely attached an old log here. That said, the courteous thing to do is indeed uncompress it so that the developers can read it easily.

As for the actual error; it is very reminiscent of one that Alex's Mobs experienced: https://github.com/Alex-the-666/AlexsMobs/issues/348
You should reference that when you report this to the Epic Fight Mod (though I suspect Spartan Weaponry may be a partial cause here).

**Comment by GirafiStudios** [comment] 2021-05-12 16:05
Closing as none of the crash points is in Atum.

**Closed by GirafiStudios** 2021-05-12 16:05 UTC
