### ISSUE TITLE
Client Crash with Mekanism

### ISSUE THREAD

**Issue by skuIIs** [TeamMetallurgy/Atum2#132] opened 2019-06-04 23:58 UTC
When right clicking Mekanism Mechanical Pipes, the client crashes. It looks like the onArmorClean event tries to evoke a fluid handler on the pipes.

[https://pastebin.com/9bPJX0tv](https://pastebin.com/9bPJX0tv)

**Comment by GirafiStudios** [comment] 2019-06-05 06:38
Thank you for the report!
This is actually caused by some Forge code not respecting their own code.
A fix will be in the next version of Atum

**Closed** 2019-06-05 06:39 UTC
