### ISSUE TITLE
Boss Invisible

### ISSUE THREAD

**Issue by Notlucky101** [TeamMetallurgy/Atum2#148] opened 2019-08-11 00:09 UTC
I cannot see Pharaoh Bak'djer. He can hit me but I cannot hit him on account I cannot see him/her
![2019-08-10_17 06 14](https://user-images.githubusercontent.com/42447191/62828043-92db2c00-bb91-11e9-99a1-e4d4f36a2a99.png)

**Comment by GirafiStudios** [comment] 2019-08-11 00:12
Thanks for your report!
Would you happen to be using Optifine?

**Comment by Notlucky101** [comment] 2019-08-11 11:58
Yes I am but my son on the other computer does not, and we both cannot see
the boss, furthermore
we are running a server.

**Comment by GirafiStudios** [comment] 2019-08-11 12:00
Are you running the server on Lan?

**Comment by Notlucky101** [comment] 2019-08-11 12:16
yes I am running a lan server

**Comment by GirafiStudios** [comment] 2019-08-11 12:33
That is most likely the problem then. A lot of thing in Forge does not work quite right on a Lan server.
Could you send me your world and coordinates to the pyramid? 
I doubt there is anything I can do about it since it's on a Lan server though, but I'll take a look.

**Comment by Notlucky101** [comment] 2019-08-11 16:23
well if say so, if that is the problem you might want to inquire to the
maker of the twilight forest, on account there was never a problem with
that mod.
and we play that on Lan all the time.

**Comment by GirafiStudios** [comment] 2019-08-11 16:49
As I said it may or may not be something I can fix.
I would need to get your world though, so I can debug it.

**Comment by GirafiStudios** [comment] 2019-08-21 11:16
Unable to reproduce the issue on a lan server.
Closing since a world was not provided as requested.

**Closed by GirafiStudios** 2019-08-21 11:16 UTC
